version: '3.8'

services:
  # VLLM服务
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "8000:8000"
    volumes:
      - /models:/models
    command: >
      --model /models/Qwen3-0.6B-GPTQ-Int8
      --host 0.0.0.0
      --port 8000
      --served-model-name Qwen3-0.6B-GPTQ-Int8
      --max-model-len 2048
      --dtype float16
      --quantization gptq
      --gpu-memory-utilization 0.8
      --max-num-seqs 256
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VLLM_API_BASE_URL=http://vllm:8000/v1
      - DATABASE_URL=sqlite:///./data/chat.db
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./data:/app/data
    depends_on:
      - vllm

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  models:
  data:
